services:

  Mooc.shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc']

  Mooc.shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Mooc.shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/InMemoryAsyncEventBus
    arguments: []
