version: '3.8'

x-app-service: &default-app
  build: .
  command: ''
  environment:
    - MONGO_URL=mongodb://mongo:27017/dev
  depends_on:
    - mongo
  volumes:
    - .:/code:delegated
    - node_modules:/code/node_modules:delegated

services:
  app:
    <<: *default-app

  mooc-backend:
    <<: *default-app
    command: bash -c "npm run build && npm run start"
    ports:
      - 3000:3000

  backoffice-frontend:
    <<: *default-app
    command: bash -c "npm run build && npm run start:backoffice:frontend"
    ports:
      - 8032:8032

  mongo:
    image: mongo:3.4.6
    volumes:
      - ./data/mongo:/data/db:delegated
    ports:
      - 27017:27017

volumes:
  node_modules:
