services:
  Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Mooc/Shared/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['mooc', '@Shared.MongoConfig']

  Shared.Logger:
    class: ../../../../../Contexts/Shared/infrastructure/WinstonLogger
    arguments: []

  Shared.RabbitMqConfig:
    factory:
      class: ../../../../../Contexts/Mooc/Shared/infrastructure/EventBus/RabbitMq/RabbitMqConfigFactory
      method: 'createConfig'

  Shared.EventBus:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMq/RabbitMqEventBus
    arguments: ['@Shared.RabbitMqConfig', '@Shared.Logger']

  Shared.CommandHandlersInformation:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlersInformation
    arguments: ['!tagged commandHandler']

  Shared.CommandBus:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Shared.CommandHandlersInformation']

  Shared.QueryHandlersInformation:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlersInformation
    arguments: ['!tagged queryHandler']

  Shared.QueryBus:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Shared.QueryHandlersInformation']
